### ISSUE TITLE
could not compile 

### ISSUE THREAD

**Issue by leecloudvictor** [friendlyarm/QtE-Demo#1]
uname -a
Linux NanoPi-M1-Plus 4.14.0 #83 SMP Fri Dec 8 17:44:19 CST 2017 armv7l armv7l armv7l GNU/Linux

root@NanoPi-M1-Plus:/opt/FriendlyARM/toolschain/4.9.3/bin# ./arm-cortexa9-linux-gnueabihf-gcc -v
-bash: ./arm-cortexa9-linux-gnueabihf-gcc: cannot execute binary file: Exec format error

**Comment by friendlyarm** [comment]
Hi,  

It is recommended that you use docker to cross-compile your qt app:
https://github.com/friendlyarm/friendlyelec-ubuntu16-docker

To build a local compilation environment, it is recommended to install ubuntu 16.04 64-bit system, and then refer to the following file to install relevant packages in ubuntu:
https://github.com/friendlyarm/friendlyelec-ubuntu16-docker/blob/master/Dockerfile

Thanks
