### ISSUE TITLE
在按要求搭建完qt交叉编译环境后，编译QtE-Demo出现编译错误

### ISSUE THREAD

**Issue by wzxgww** [friendlyarm/QtE-Demo#2]
在按要求搭建完qt交叉编译环境后，编译QtE-Demo出现编译错误：
/usr/lib/gcc-cross/arm-linux-gnueabihf/5/../../../../arm-linux-gnueabihf/bin/ld.gold: fatal error: --sysroot=: must take a non-empty argument
collect2: error: ld returned 1 exit status

另外，apt下载的交叉编译器与给的Qt-5.10.0-nexell32-sdk但ABI不一致。

**Comment by friendlyarm** [comment]
多谢反馈，编译问题已经修复，请执行一次 git pull 。

建议使用 docker 环境进行编译：
https://github.com/friendlyarm/friendlyelec-ubuntu16-docker

自已搭建环境的话，建议安装 ubuntu 16.04 64位系统，然后参考下面这个文件的内容，在 ubuntu 里安装相关的软件包：
https://github.com/friendlyarm/friendlyelec-ubuntu16-docker/blob/master/Dockerfile
